### ISSUE TITLE
Minions

### ISSUE THREAD

**Issue by Charles-Foster-Kane** [MightyDuelsDevs/MightyDuelsDistributed#12]
### Minions

_Er moet ondersteuning voor minions toe gevoegd worden_
### Mogelijke oplossing

_De GUI moet minions kunnen weergeven en behandelen en de backend moet Minions kunnen verwerken._
### Bestanden
- GUI Controller
- Match.java
### assigment
- @0RIck0
- @MatthijsZelluf 
### info
- Door: Rick
- Datum: 16-11-2015

**Comment by Charles-Foster-Kane** [comment]
probleem met de buttons voor de kaarten krijgen

Oplossingen:
- buttons elke keer weer voor de kaart leggen
- de kaarten een onclick event geven
- twéé grid's voorste is voor buttons. achterste is voor kaarten

**Comment by MartijnVanBuul** [comment]
De kaarten kunnen verplaats worden in de MatchController door de methode placeMinionCards(). Dit moet even getest worden om te checken of het nog werkt.
