### ISSUE TITLE
Als de speler opgeeft in de eerste beurt krijgt hij gelijkspel.

### ISSUE THREAD

**Issue by MartijnVanBuul** [MightyDuelsDevs/MightyDuelsDistributed#15]
### naam

Als de speler meteen opgeeft aan het begin van de match(eerste beurt) krijgt hij een gelijkspel.
### Mogelijke oplossing

Beter checken bij de SocketClient.
### Bestanden
- Server.SocketManagerServer
### assigment
- @MartijnVanBuul
### info
- Door: Martijn van Buul
- Datum: 11/01/2016

**Comment by MartijnVanBuul** [comment]
Leek alleen te gebeuren toen qweqwe1 en qweqwe2 tegen elkaar speelden. Het probleem was er niet toen janssen en qweqwe2 tegen elkaar speelden.

**Comment by Charles-Foster-Kane** [comment]
niet repliceerbaar
