### ISSUE TITLE
dubbele hero node

### ISSUE THREAD

**Issue by Charles-Foster-Kane** [MightyDuelsDevs/MightyDuelsDistributed#25]
### dubbele hero node

_1 enemy hero node word 2 keer aangemaakt_
### Mogelijke oplossing

_kijken waarom bij 1 van de clients de hero node 2 keer word toegevoegd_
### Bestanden
- ?
### assigment
- @MartijnVanBuul 
- @TenshiIT
### info
- Door: Ramòn
- Datum: 19-11-2015*

**Comment by MartijnVanBuul** [comment]
Lijkt te liggen aan een match die nog runt op de achtergrond. Bij het afsluiten van een client moet ook de match worden verwijderd en worden afgerond.

**Comment by Charles-Foster-Kane** [comment]
fixed de verloren player bleef in de list staan en is weg gehaald
