### ISSUE TITLE
Hover over cards highlight

### ISSUE THREAD

**Issue by Charles-Foster-Kane** [MightyDuelsDevs/MightyDuelsDistributed#27]
### Hover over cards highlight

_zodra je over een kaart hovert zou er feedback moeten komen in de vorm van een highlight_
### Mogelijke oplossing

_https://blog.idrsolutions.com/2014/02/tutorial-create-border-glow-effect-javafx/_
### Bestanden
- Cardcontrol
### assigment
- @MartijnVanBuul 
- @TenshiIT
### info
- Door: Ramòn
- Datum: 19-11-2015*

**Comment by 0Rick0** [comment]
commit d050e445a5571282a161c282b72af2a000ad9d96
