### ISSUE TITLE
Chatten

### ISSUE THREAD

**Issue by Charles-Foster-Kane** [MightyDuelsDevs/MightyDuelsDistributed#6]
### Chatten

*er moet een chat via *
### Mogelijke oplossing

_
- creëren van de methodes voor te chatten
  _
### Bestanden
- ?
### assigment
- @ 
### info
- Door: Ramòn
- Datum: 11-1-2016

**Comment by 0Rick0** [comment]
now capable of sending messages

**Comment by Charles-Foster-Kane** [comment]
beautification!
